### ISSUE TITLE
Flutter example crash

### ISSUE THREAD

**Issue by Nillouise** [biezhihua/libdsm#1]
After I import the example/example_flutter in android studio, I run it and press the create button.App crash. (I think I shold import the aar file, but I try it and not import successful).

the crash message I will put later.

**Comment by Nillouise** [comment]
```
**Crash message:**
I/DsmPlugin(24043): onMethodCall() called with: call.method = [DSM_init], call.args = [null]
E/flutter (24043): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.example_flutter-ok6O7ZznrsOAQ87L9gG68g==/base.apk"],nativeLibraryDirectories=[/data/app/com.example.example_flutter-ok6O7ZznrsOAQ87L9gG68g==/lib/x86, /data/app/com.example.example_flutter-ok6O7ZznrsOAQ87L9gG68g==/base.apk!/lib/x86, /system/lib, /system/product/lib]]] couldn't find "libopen_dsm.so"
E/flutter (24043): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
E/flutter (24043): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
E/flutter (24043): 	at java.lang.System.loadLibrary(System.java:1667)
E/flutter (24043): 	at open.android.lib.dsm.Dsm.<clinit>(Dsm.kt:236)
E/flutter (24043): 	at open.flutter.libdsm.DsmPlugin.onMethodCall(DsmPlugin.kt:56)
E/flutter (24043): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
E/flutter (24043): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
E/flutter (24043): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
E/flutter (24043): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (24043): 	at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter (24043): 	at android.os.Looper.loop(Looper.java:174)
E/flutter (24043): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
E/flutter (24043): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (24043): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter (24043): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter (24043): 
F/flutter (24043): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env). 
F/libc    (24043): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 24043 (example_flutter), pid 24043 (example_flutter)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'google/sdk_gphone_x86/generic_x86:10/QSR1.191030.002/5978551:userdebug/dev-keys'
Revision: '0'
ABI: 'x86'
Timestamp: 2020-05-16 10:32:33+0000
pid: 24043, tid: 24043, name: example_flutter  >>> com.example.example_flutter <<<
uid: 10138
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env). 
'
    eax 00000000  ebx 00005deb  ecx 00005deb  edx 00000006
    edi f5f0333e  esi ffbbbd60
    ebp f7270ad0  esp ffbbbd08  eip f7270ad9
backtrace:
```

**Comment by biezhihua** [comment]
I will deal with it as soon as possible

**Comment by biezhihua** [comment]
Hey, do you run it in an emulator?

For the LIBDSM library, it does not yet support the x86 architecture or its emulator counterpart.

@Nillouise

**Comment by Nillouise** [comment]
Yes, I run it in emulator of android studio, it is an x86 emulator.

I get it,thank for the reply.

**Comment by biezhihua** [comment]
already support emulator

**Comment by biezhihua** [comment]
@Nillouise
